version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: budget-app-postgres
    restart: always
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budget_app"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: 